# Generated by Django 5.0.13 on 2025-04-26 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("nomor", models.CharField(max_length=255)),
                ("pemilik", models.CharField(max_length=255)),
                ("saldo", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Hutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="HutangPiutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
                (
                    "tipe",
                    models.CharField(
                        choices=[("hutang", "Hutang"), ("piutang", "Piutang")],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Piutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_bayar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_bayar", models.BooleanField(default=False)),
                ("tanggal_bayar", models.DateField(auto_now_add=True)),
                (
                    "bukti_pembayaran",
                    models.FileField(
                        blank=True, null=True, upload_to="bukti_pembayaran/"
                    ),
                ),
                ("tanggal_verifikasi", models.DateField(blank=True, null=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("kelas", models.CharField(max_length=50)),
                ("no_rekening", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PembayaranSPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bulan",
                    models.CharField(
                        choices=[
                            ("01", "Januari"),
                            ("02", "Februari"),
                            ("03", "Maret"),
                            ("04", "April"),
                            ("05", "Mei"),
                            ("06", "Juni"),
                            ("07", "Juli"),
                            ("08", "Agustus"),
                            ("09", "September"),
                            ("10", "Oktober"),
                            ("11", "November"),
                            ("12", "Desember"),
                        ],
                        max_length=2,
                    ),
                ),
                ("jumlah_bayar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status_bayar",
                    models.CharField(
                        choices=[("belum lunas", "Belum Lunas"), ("lunas", "Lunas")],
                        default="belum lunas",
                        max_length=20,
                    ),
                ),
                ("tanggal_bayar", models.DateField(auto_now_add=True)),
                (
                    "bukti_pembayaran",
                    models.ImageField(
                        blank=True, null=True, upload_to="bukti_pembayaran/"
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.siswa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateTimeField()),
                (
                    "jenis",
                    models.CharField(
                        choices=[
                            ("pemasukan", "Pemasukan"),
                            ("pengeluaran", "Pengeluaran"),
                        ],
                        max_length=20,
                    ),
                ),
                ("jumlah", models.IntegerField()),
                ("keterangan", models.TextField()),
                ("bukti", models.CharField(blank=True, max_length=255, null=True)),
                ("nominal", models.BigIntegerField(default=0)),
                (
                    "bank",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.bank"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="keuangan.kategori",
                    ),
                ),
            ],
        ),
    ]
