# Generated by Django 5.0.13 on 2025-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LaporanKeuangan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(auto_now_add=True)),
                (
                    "pemasukan",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "pengeluaran",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
    ]
