# Generated by Django 5.0.13 on 2025-05-03 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0002_laporankeuangan"),
    ]

    operations = [
        migrations.CreateModel(
            name="PenarikanTabungan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal_penarikan", models.DateField(auto_now_add=True)),
                ("jumlah_ditarik", models.IntegerField()),
                ("keterangan", models.TextField(blank=True, null=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.siswa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TabunganSiswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(unique=True)),
                ("nominal", models.IntegerField(default=5000)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.siswa"
                    ),
                ),
            ],
            options={
                "unique_together": {("siswa", "tanggal")},
            },
        ),
    ]
