# Generated by Django 5.0.13 on 2025-05-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0003_penarikantabungan_tabungansiswa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tabungansiswa",
            name="tanggal",
            field=models.DateField(),
        ),
    ]
