# Generated by Django 5.0.13 on 2025-04-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0003_alter_transaksi_tanggal"),
    ]

    operations = [
        migrations.CreateModel(
            name="HutangPiutang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField()),
                ("nominal", models.IntegerField()),
                ("keterangan", models.TextField()),
                (
                    "tipe",
                    models.CharField(
                        choices=[("hutang", "Hutang"), ("piutang", "Piutang")],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
