# Generated by Django 5.0.13 on 2025-05-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0004_alter_tabungansiswa_tanggal"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabungansiswa",
            name="tarik",
            field=models.BooleanField(default=False),
        ),
    ]
