# Generated by Django 5.0.13 on 2025-04-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0004_hutangpiutang"),
    ]

    operations = [
        migrations.CreateModel(
            name="Siswa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("no_rekening", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PembayaranSPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bulan",
                    models.CharField(
                        choices=[
                            ("01", "Januari"),
                            ("02", "Februari"),
                            ("03", "Maret"),
                            ("04", "April"),
                            ("05", "Mei"),
                            ("06", "Juni"),
                            ("07", "Juli"),
                            ("08", "Agustus"),
                            ("09", "September"),
                            ("10", "Oktober"),
                            ("11", "November"),
                            ("12", "Desember"),
                        ],
                        max_length=2,
                    ),
                ),
                ("jumlah_bayar", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status_bayar",
                    models.CharField(
                        choices=[("belum lunas", "Belum Lunas"), ("lunas", "Lunas")],
                        default="belum lunas",
                        max_length=20,
                    ),
                ),
                ("tanggal_bayar", models.DateField(auto_now_add=True)),
                (
                    "bukti_pembayaran",
                    models.ImageField(
                        blank=True, null=True, upload_to="bukti_pembayaran/"
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.siswa"
                    ),
                ),
            ],
        ),
    ]
