# Generated by Django 5.0.13 on 2025-05-20 03:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0005_tabungansiswa_tarik"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_tagihan",
                    models.DecimalField(
                        decimal_places=2, default=3000000, max_digits=10
                    ),
                ),
                ("tanggal_mulai", models.DateField(default=django.utils.timezone.now)),
                ("jatuh_tempo", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("belum lunas", "Belum Lunas"), ("lunas", "Lunas")],
                        default="belum lunas",
                        max_length=20,
                    ),
                ),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.siswa"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DSPCicilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(auto_now_add=True)),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bukti_pembayaran",
                    models.ImageField(blank=True, null=True, upload_to="bukti_dsp/"),
                ),
                (
                    "dsp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.dsp"
                    ),
                ),
            ],
        ),
    ]
