# Generated by Django 4.2.7 on 2025-04-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0006_alter_siswa_user_userprofile_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
