# Generated by Django 5.0.13 on 2025-05-21 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0006_dsp_dspcicilan"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DSPCicilan",
        ),
    ]
