# Generated by Django 5.0.13 on 2025-05-21 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0007_delete_dspcicilan"),
    ]

    operations = [
        migrations.CreateModel(
            name="DSPCicilan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tanggal", models.DateField(auto_now_add=True)),
                ("jumlah", models.DecimalField(decimal_places=2, max_digits=10)),
                ("bukti_pembayaran", models.ImageField(upload_to="bukti_dsp/")),
                (
                    "dsp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="keuangan.dsp"
                    ),
                ),
            ],
        ),
    ]
