# Generated by Django 5.0.13 on 2025-04-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0007_delete_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pembayaran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah_bayar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status_bayar", models.BooleanField(default=False)),
                ("tanggal_bayar", models.DateField(auto_now_add=True)),
                (
                    "bukti_pembayaran",
                    models.FileField(
                        blank=True, null=True, upload_to="bukti_pembayaran/"
                    ),
                ),
                ("tanggal_verifikasi", models.DateField(blank=True, null=True)),
                (
                    "siswa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
