# Generated by Django 5.0.13 on 2025-06-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keuangan", "0009_ppdb_ppdbcicilan"),
    ]

    operations = [
        migrations.AddField(
            model_name="dspcicilan",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pembayaran",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="pembayaranspp",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="penarikantabungan",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ppdbcicilan",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tabungansiswa",
            name="is_posted_to_laporan_keuangan",
            field=models.BooleanField(default=False),
        ),
    ]
